### ISSUE TITLE
unable to copy

### ISSUE THREAD

**Issue by nooob0** [SingularReza/drive-folder-copier#9]
Traceback (most recent call last):
  File "final.py", line 73, in <module>
    replicate(folderid, destid, driveid)
  File "final.py", line 41, in replicate
    'name': parentitem['name'],
TypeError: 'HttpRequest' object is not subscriptable

this is the error showin up after i enter 3 required values

**Comment by SingularReza** [comment]
> Traceback (most recent call last):
> File "final.py", line 73, in
> replicate(folderid, destid, driveid)
> File "final.py", line 41, in replicate
> 'name': parentitem['name'],
> TypeError: 'HttpRequest' object is not subscriptable
> 
> this is the error showin up after i enter 3 required values

Lol, I forgot to push the working version 2 years ago. It should work now and anyway there are better alternatives. Use the free version of airexplorer for these kind of things involving cloud storage
